[package]
name = "rust-redis-docker"
version = "0.1.0"
authors = ["Kevin Wang <kwangsan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
redis = "0.16.0"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

[dependencies.listenfd]
version = "0.3"

[source.crates-io]
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = '/usr/src/app/vendor'

[[bin]]
name = "rust-redis-docker"
path = "src/main.rs"
